### ISSUE TITLE
[Epic] Data Pipeline for RLHF Tuning

### ISSUE THREAD

**Issue by RobotSail** [instructlab/ui#392]
In order to perform RLHF, we would like to collect feedback on human preference when tuning models. In order to accomplish this, there are a number of steps which must first be completed to allow the UI to support this. 

We define the epic as follows: 

- [ ] Add support for persistent storage via a database
- [ ] Store a user's chat conversations in persistent storage
- [ ] Collect unpaired preference feedback
- [ ] Collect paired preference feedback

The implementations are left as exercises for the reader
